POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

{
    "username": "ashish prajapat",
    "password": "ashish@123",
    "email": "prajapatashish507@gmail.com",
    "name": "Ashish prajapat"
}

###




POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

{
    "email":"prajapatashish507@gmail.com",
    "password":"ashish@123"
}

###
POST http://localhost:3000/update_profile_picture HTTP/1.1
Content-Type: application/json
Authorization: Bearer <token>

{
    "token": "efd15d6587eb6a6a51a54a5f61e43b7cf60df741734a2961da698c2ef61f9f4e"
}